version: '2'
services:
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=vetManager13
      - MYSQL_DATABASE=vetmanager
      - MYSQL_USER=vetmanager
      - MYSQL_PASSWORD=vetManagerRemoteConnect1on
    expose:
      - 3306
  mongo:
    image: khezen/mongo:3.4
    environment:
      - AUTH=y
      - ADMIN_USER=vetmanager
      - ADMIN_PASSWORD=vetManager13
      - DB_NAME=vetManagerSaaS
      - DB_USER=vetmanager
      - DB_PWD=vetManagerRemoteConnect1on
    expose:
      - 27017
  iservice:
    image: iservice:1.0
    ports:
      - 4444
  webservice:
    image: webservice:1.1
    depends_on:
    - mariadb
    - mongo
    - iservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mariadb/vetmanager
      spring.data.mongodb.host: mongo
    ports:
     - "8443:8990"
