version: '3'

services:
  haproxy:
    image: haproxy:alpine
    ports:
      - 80:80
      - 443:443
    links:
      - webservice1
      - webservice2
    volumes:
      - ./haproxy/local:/usr/local/etc/haproxy/
  redis:
      image: redis:3.0.3
      hostname: redis
      expose:
        - 6379
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=vetManager13
      - MYSQL_DATABASE=vetmanager
      - MYSQL_USER=vetmanager
      - MYSQL_PASSWORD=vetManagerRemoteConnect1on
    expose:
      - 3306

  mongo:
    image: khezen/mongo:3.4
    environment:
      - AUTH=y
      - ADMIN_USER=vetmanager
      - ADMIN_PASSWORD=vetManager13
      - DB_NAME=vetManagerSaaS
      - DB_USER=vetmanager
      - DB_PWD=vetManagerRemoteConnect1on
    expose:
      - 27017

  iservice:
    image: iservice:1.1
    ports:
      - 8083

  webservice1:
    image: webservice:1.1
    depends_on:
    - mariadb
    - mongo
    - iservice
    - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mariadb/vetmanager
      spring.data.mongodb.host: mongo
      spring.redis.host: redis
    ports:
     - 8990

  webservice2:
    image: webservice:1.1
    depends_on:
    - mariadb
    - mongo
    - iservice
    - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mariadb/vetmanager
      spring.data.mongodb.host: mongo
      spring.redis.host: redis
    ports:
     - 8990



