jobs: 
  build: 
    docker: 
      - 
        image: "circleci/openjdk:8-jdk"

    working_directory: ~/repo

    environment: 
      MAVEN_OPTS: "-Xmx3200m"

    steps: 
      - checkout

      - 
        restore_cache: 
          keys: 
            - "v1-dependencies-{{ checksum \"pom.xml\" }}"
            - v1-dependencies-
      - 
        run: "mvn dependency:go-offline"
      - 
        save_cache: 
          key: "v1-dependencies-{{ checksum \"pom.xml\" }}"
          paths: 
            - ~/.m2
      - 
        run: "mvn package -Dmaven.test.skip=true"

      - save_cache:
          key: target
          paths:
            - target/vetmanager-0.0.1-SNAPSHOT.jar
  deploy: 
    docker: 
      - 
        image: "docker:stable"
    steps: 
      - restore_cache:
            keys:
              - target/vetmanager-0.0.1-SNAPSHOT.jar-{{ checksum "vetmanager-0.0.1-SNAPSHOT.jar" }}
              - target/vetmanager-0.0.1-SNAPSHOT.jar
      - 
        attach_workspace:
          at: "~"
      - 
        run: 
          name: "Build Docker image"
          command: "docker build -t mtenrero/vetmanager-webservice:latest -t mtenrero/vetmanager-webservice:`git show --format=\"%h\" --no-patch` ."
      - 
        run: 
          name: "Tag Docker image"
          command: "docker tag mtenrero/vetmanager-webservice:latest localhost:5000/mtenrero/vetmanager-webservice:latest"
      - 
        deploy: 
          name: "Create SSH Tunnel"
          command: "ssh -nNT -L 5000:$HOST_IP:5000 $HOST_USER@$HOST_IP"
          background: true
      - 
        deploy: 
          name: "Deploy to private registry"
          command: "docker push localhost:5000/mtenrero/vetmanager-webservice:latest"
workflows:
  version: 2 
  build-deploy: 
    jobs: 
      - build
      - deploy:
          requires:
            - build
