#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run compilation!
      - run: mvn package -Dmaven.test.skip=true

      - run:
          name: Build Docker image
          command: docker build -t mtenrero/vetmanager-webservice:latest -t mtenrero/vetmanager-webservice:`git show --format="%h" --no-patch` .

      - run:
          name: Tag Docker image
          command: docker tag mtenrero/vetmanager-webservice:latest localhost:5000/mtenrero/vetmanager-webservice:latest

      - deploy:
          name: Create SSH Tunnel
          command: ssh -nNT -L 5000:$HOST_IP:5000 $HOST_USER@$HOST_IP
          background: true 
      
      - deploy: 
          name: Deploy to private registry
          command: docker push localhost:5000/mtenrero/vetmanager-webservice:latest